use sd2dinit::model::{DinitService, DinitType, RestartPolicy};
use sd2dinit::generator::generate;
use std::path::PathBuf;

fn minimal_service() -> DinitService {
    DinitService {
        name: "test".into(),
        source_path: PathBuf::from("/usr/lib/systemd/system/test.service"),
        service_type: DinitType::Process,
        command: Some("/usr/bin/test-daemon".into()),
        stop_command: None,
        user: None,
        group: None,
        working_dir: None,
        env_files: Vec::new(),
        pid_file: None,
        restart: RestartPolicy::Never,
        smooth_recovery: false,
        restart_delay: None,
        depends_on: Vec::new(),
        depends_ms: Vec::new(),
        waits_for: Vec::new(),
        logfile: None,
    }
}

#[test]
fn test_generate_minimal_service() {
    let svc = minimal_service();
    let output = generate(&svc);

    assert!(output.starts_with("# Generated by sd2dinit from /usr/lib/systemd/system/test.service\n"));
    assert!(output.contains("type = process\n"));
    assert!(output.contains("command = /usr/bin/test-daemon\n"));
    // Should NOT contain keys for None/default fields
    assert!(!output.contains("stop-command"));
    assert!(!output.contains("run-as"));
    assert!(!output.contains("working-dir"));
    assert!(!output.contains("env-file"));
    assert!(!output.contains("pid-file"));
    assert!(!output.contains("restart-delay"));
    assert!(!output.contains("logfile"));
}

#[test]
fn test_generate_restart_false_omitted() {
    let svc = minimal_service();
    let output = generate(&svc);
    // restart = false is the default in dinit, so we don't emit it
    assert!(!output.contains("restart"));
    assert!(!output.contains("smooth-recovery"));
}

#[test]
fn test_generate_restart_always() {
    let mut svc = minimal_service();
    svc.restart = RestartPolicy::Always;
    svc.smooth_recovery = true;
    svc.restart_delay = Some(5.0);
    let output = generate(&svc);

    assert!(output.contains("restart = true\n"));
    assert!(output.contains("smooth-recovery = true\n"));
    assert!(output.contains("restart-delay = 5\n"));
}

#[test]
fn test_generate_restart_on_failure() {
    let mut svc = minimal_service();
    svc.restart = RestartPolicy::OnFailure;
    svc.smooth_recovery = true;
    let output = generate(&svc);
    assert!(output.contains("restart = on-failure\n"));
    assert!(output.contains("smooth-recovery = true\n"));
}

#[test]
fn test_generate_run_as_user_and_group() {
    let mut svc = minimal_service();
    svc.user = Some("www-data".into());
    svc.group = Some("www-data".into());
    let output = generate(&svc);
    assert!(output.contains("run-as = www-data:www-data\n"));
}

#[test]
fn test_generate_run_as_user_only() {
    let mut svc = minimal_service();
    svc.user = Some("nobody".into());
    let output = generate(&svc);
    assert!(output.contains("run-as = nobody\n"));
}

#[test]
fn test_generate_run_as_group_only() {
    let mut svc = minimal_service();
    svc.group = Some("daemon".into());
    let output = generate(&svc);
    assert!(output.contains("run-as = :daemon\n"));
}

#[test]
fn test_generate_bgprocess_with_pid_file() {
    let mut svc = minimal_service();
    svc.service_type = DinitType::BgProcess;
    svc.pid_file = Some(PathBuf::from("/run/nginx.pid"));
    let output = generate(&svc);
    assert!(output.contains("type = bgprocess\n"));
    assert!(output.contains("pid-file = /run/nginx.pid\n"));
}

#[test]
fn test_generate_dependencies() {
    let mut svc = minimal_service();
    svc.depends_on = vec!["network".into(), "sshd-pre".into()];
    svc.depends_ms = vec!["dbus".into()];
    svc.waits_for = vec!["local-fs".into()];
    let output = generate(&svc);
    assert!(output.contains("depends-on = network\n"));
    assert!(output.contains("depends-on = sshd-pre\n"));
    assert!(output.contains("depends-ms = dbus\n"));
    assert!(output.contains("waits-for = local-fs\n"));
}

#[test]
fn test_generate_multiple_env_files() {
    let mut svc = minimal_service();
    svc.env_files = vec![
        PathBuf::from("/etc/dinit.d/sshd.env"),
        PathBuf::from("/etc/default/sshd"),
    ];
    let output = generate(&svc);
    assert!(output.contains("env-file = /etc/dinit.d/sshd.env\n"));
    assert!(output.contains("env-file = /etc/default/sshd\n"));
}

#[test]
fn test_generate_full_service() {
    let svc = DinitService {
        name: "sshd".into(),
        source_path: PathBuf::from("/usr/lib/systemd/system/sshd.service"),
        service_type: DinitType::Process,
        command: Some("/usr/bin/sshd -D".into()),
        stop_command: Some("/bin/kill -QUIT $PID".into()),
        user: Some("root".into()),
        group: None,
        working_dir: Some(PathBuf::from("/var/run/sshd")),
        env_files: vec![PathBuf::from("/etc/dinit.d/sshd.env")],
        pid_file: None,
        restart: RestartPolicy::OnFailure,
        smooth_recovery: true,
        restart_delay: Some(2.5),
        depends_on: vec!["network".into()],
        depends_ms: Vec::new(),
        waits_for: vec!["sshd-pre".into()],
        logfile: Some(PathBuf::from("/var/log/sshd.log")),
    };
    let output = generate(&svc);

    assert!(output.contains("type = process\n"));
    assert!(output.contains("command = /usr/bin/sshd -D\n"));
    assert!(output.contains("stop-command = /bin/kill -QUIT $PID\n"));
    assert!(output.contains("run-as = root\n"));
    assert!(output.contains("working-dir = /var/run/sshd\n"));
    assert!(output.contains("logfile = /var/log/sshd.log\n"));
    assert!(!output.contains("pid-file")); // pid_file is None
    assert!(output.contains("env-file = /etc/dinit.d/sshd.env\n"));
    assert!(output.contains("restart = on-failure\n"));
    assert!(output.contains("smooth-recovery = true\n"));
    assert!(output.contains("restart-delay = 2.5\n"));
    assert!(output.contains("depends-on = network\n"));
    assert!(output.contains("waits-for = sshd-pre\n"));
}

#[test]
fn test_generate_restart_delay_whole_number() {
    let mut svc = minimal_service();
    svc.restart = RestartPolicy::Always;
    svc.restart_delay = Some(5.0);
    let output = generate(&svc);
    // 5.0 should render as "5", not "5.0"
    assert!(output.contains("restart-delay = 5\n"));
    assert!(!output.contains("restart-delay = 5.0"));
}

#[test]
fn test_generate_restart_delay_fractional() {
    let mut svc = minimal_service();
    svc.restart = RestartPolicy::Always;
    svc.restart_delay = Some(2.5);
    let output = generate(&svc);
    assert!(output.contains("restart-delay = 2.5\n"));
}
