use sd2dinit::config::Config;
use sd2dinit::converter;
use sd2dinit::generator;
use sd2dinit::parser::SystemdUnit;
use std::path::PathBuf;

fn full_convert(input: &str, filename: &str) -> (String, Vec<sd2dinit::model::Warning>) {
    let unit = SystemdUnit::parse(input, PathBuf::from(filename)).unwrap();
    let config = Config::default();
    let result = converter::convert(&unit, &config).unwrap();
    (generator::generate(&result.main_service), result.warnings)
}

#[test]
fn test_integration_sshd() {
    let input = "\
[Unit]
Description=OpenSSH Daemon
Wants=sshdgenkeys.service
After=sshdgenkeys.service
After=network.target

[Service]
ExecStart=/usr/bin/sshd -D
ExecReload=/bin/kill -HUP $MAINPID
Restart=always

[Install]
WantedBy=multi-user.target
";
    let (output, _warnings) = full_convert(input, "/usr/lib/systemd/system/sshd.service");

    assert!(output.starts_with("# Generated by sd2dinit from /usr/lib/systemd/system/sshd.service\n"));
    assert!(output.contains("type = process\n"));
    assert!(output.contains("command = /usr/bin/sshd -D\n"));
    assert!(output.contains("restart = true\n"));
    assert!(output.contains("smooth-recovery = true\n"));
    assert!(output.contains("depends-ms = sshdgenkeys\n"));
    assert!(output.contains("waits-for = sshdgenkeys\n"));
    assert!(output.contains("waits-for = network\n"));
}

#[test]
fn test_integration_nginx_forking() {
    let input = "\
[Unit]
Description=A high performance web server
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/bin/nginx -t -q
ExecStart=/usr/bin/nginx
ExecStop=/bin/kill -s QUIT $MAINPID
User=root

[Install]
WantedBy=multi-user.target
";
    let unit = SystemdUnit::parse(input, PathBuf::from("/usr/lib/systemd/system/nginx.service")).unwrap();
    let config = Config::default();
    let result = converter::convert(&unit, &config).unwrap();
    let output = generator::generate(&result.main_service);

    assert!(output.contains("type = bgprocess\n"));
    assert!(output.contains("pid-file = /run/nginx.pid\n"));
    assert!(output.contains("command = /usr/bin/nginx\n"));
    assert!(output.contains("stop-command = /bin/kill -s QUIT $MAINPID\n"));
    assert!(output.contains("run-as = root\n"));
    // Pre service generated for ExecStartPre
    assert!(result.pre_service.is_some());
    assert!(output.contains("depends-on = nginx-pre\n"));
    // network-online.target → network
    assert!(output.contains("depends-ms = network\n"));
    assert!(output.contains("waits-for = network\n"));
    // should_enable from WantedBy
    assert!(result.should_enable);
}

#[test]
fn test_integration_docker_notify_fallback() {
    let input = "\
[Unit]
Description=Docker Application Container Engine
After=network-online.target containerd.service
Wants=network-online.target containerd.service
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/dockerd -H fd://
Restart=always
RestartSec=2
TasksMax=infinity
Delegate=yes
OOMScoreAdjust=-500

[Install]
WantedBy=multi-user.target
";
    let (output, warnings) = full_convert(input, "/usr/lib/systemd/system/docker.service");

    // notify falls back to process
    assert!(output.contains("type = process\n"));
    assert!(output.contains("restart = true\n"));
    assert!(output.contains("restart-delay = 2\n"));
    // docker.socket → docker (strip .socket suffix not in dep map, strip .socket)
    assert!(output.contains("depends-on = docker\n"));
    // network-online.target → network
    assert!(output.contains("depends-ms = network\n"));
    assert!(output.contains("depends-ms = containerd\n"));
    // notify warning
    assert!(warnings.iter().any(|w| w.message.contains("notify")));
    // cgroup warnings for TasksMax, Delegate
    assert!(warnings.iter().any(|w| w.directive == "TasksMax"));
    assert!(warnings.iter().any(|w| w.directive == "Delegate"));
}

#[test]
fn test_integration_oneshot_with_environment() {
    let input = "\
[Unit]
Description=Setup tmpfiles

[Service]
Type=oneshot
ExecStart=/usr/bin/systemd-tmpfiles --create
Environment=TMPDIR=/tmp
Environment=LANG=C
EnvironmentFile=/etc/locale.conf
WorkingDirectory=/
";
    let unit = SystemdUnit::parse(input, PathBuf::from("/usr/lib/systemd/system/tmpfiles.service")).unwrap();
    let config = Config::default();
    let result = converter::convert(&unit, &config).unwrap();
    let output = generator::generate(&result.main_service);

    assert!(output.contains("type = scripted\n"));
    assert!(output.contains("working-dir = /\n"));
    // Generated env file with single-quoted values; /etc/locale.conf does not
    // exist in the test environment so is skipped with an info warning.
    assert!(result.env_file_content.is_some());
    let env = result.env_file_content.unwrap();
    assert!(env.contains("TMPDIR='/tmp'"), "env was: {env}");
    assert!(env.contains("LANG='C'"), "env was: {env}");
    assert_eq!(result.main_service.env_files.len(), 1);
    assert!(result.main_service.env_files[0].to_str().unwrap().ends_with("tmpfiles.env"));
}

#[test]
fn test_integration_drop_in_override() {
    let base = "\
[Service]
Type=simple
ExecStart=/usr/bin/original-daemon
ExecStartPre=/usr/bin/original-setup
Restart=no
";
    let drop_in = "\
[Service]
ExecStartPre=
ExecStartPre=/usr/bin/custom-setup
Restart=always
";
    let mut unit = SystemdUnit::parse(base, PathBuf::from("/usr/lib/systemd/system/myapp.service")).unwrap();
    unit.merge_drop_in(drop_in, PathBuf::from("/etc/systemd/system/myapp.service.d/override.conf"));

    let config = Config::default();
    let result = converter::convert(&unit, &config).unwrap();
    let output = generator::generate(&result.main_service);

    // ExecStart unchanged (not reset in drop-in)
    assert!(output.contains("command = /usr/bin/original-daemon\n"));
    // Restart was overridden
    assert!(output.contains("restart = true\n"));
    // Pre service uses the custom command, not the original
    assert!(result.pre_service.is_some());
    let pre = result.pre_service.unwrap();
    assert!(pre.command.as_deref().unwrap_or("").contains("custom-setup"));
}

#[test]
fn test_integration_mixed_pre_wrapper_script() {
    let input = "\
[Service]
ExecStartPre=/usr/bin/must-work
ExecStartPre=-/usr/bin/optional
ExecStart=/usr/bin/daemon
";
    let unit = SystemdUnit::parse(input, PathBuf::from("/usr/lib/systemd/system/mixed.service")).unwrap();
    let config = Config::default();
    let result = converter::convert(&unit, &config).unwrap();

    assert!(result.pre_script.is_some());
    let script = result.pre_script.unwrap();
    assert!(script.starts_with("#!/bin/sh\nset -e\n"));
    assert!(script.contains("/usr/bin/must-work\n"));
    assert!(script.contains("/usr/bin/optional || true\n"));
    // Main depends on pre
    assert!(result.main_service.depends_on.contains(&"mixed-pre".to_string()));
}

#[test]
fn test_integration_aur_typical_service() {
    // A typical AUR service with common patterns
    let input = "\
[Unit]
Description=My AUR Application
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=myapp
Group=myapp
WorkingDirectory=/var/lib/myapp
ExecStart=/usr/bin/myapp --config /etc/myapp/config.toml
ExecStop=/usr/bin/myapp-stop
Restart=on-failure
RestartSec=10
Environment=MYAPP_ENV=production
EnvironmentFile=/etc/myapp/environment

[Install]
WantedBy=multi-user.target
";
    let unit = SystemdUnit::parse(input, PathBuf::from("/usr/lib/systemd/system/myapp.service")).unwrap();
    let config = Config::default();
    let result = converter::convert(&unit, &config).unwrap();
    let output = generator::generate(&result.main_service);

    assert!(output.contains("type = process\n"));
    assert!(output.contains("command = /usr/bin/myapp --config /etc/myapp/config.toml\n"));
    assert!(output.contains("stop-command = /usr/bin/myapp-stop\n"));
    assert!(output.contains("run-as = myapp:myapp\n"));
    assert!(output.contains("working-dir = /var/lib/myapp\n"));
    assert!(output.contains("restart = on-failure\n"));
    assert!(output.contains("smooth-recovery = true\n"));
    assert!(output.contains("restart-delay = 10\n"));
    assert!(output.contains("waits-for = network\n"));
    assert!(output.contains("depends-ms = network\n"));
    // Environment= generates .env with single-quoted value;
    // /etc/myapp/environment does not exist so EnvironmentFile= is skipped.
    assert!(result.env_file_content.is_some());
    assert!(result.env_file_content.unwrap().contains("MYAPP_ENV='production'"));
    assert!(result.main_service.env_files.len() == 1);
    assert!(result.should_enable);
}
