// SPDX-FileCopyrightText: Hadi Cherkaoui <contact@hide.cherkaoui.ch>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

use crate::model::{DinitService, DinitType, RestartPolicy};

pub fn generate(service: &DinitService) -> String {
    let mut out = String::new();

    // Provenance comment
    out.push_str(&format!(
        "# Generated by sd2dinit from {}\n",
        service.source_path.display()
    ));

    // Type
    let type_str = match service.service_type {
        DinitType::Process => "process",
        DinitType::BgProcess => "bgprocess",
        DinitType::Scripted => "scripted",
    };
    out.push_str(&format!("type = {}\n", type_str));

    // Command
    if let Some(ref cmd) = service.command {
        out.push_str(&format!("command = {}\n", cmd));
    }

    // Stop command
    if let Some(ref cmd) = service.stop_command {
        out.push_str(&format!("stop-command = {}\n", cmd));
    }

    // Run-as
    if let Some(ref user) = service.user {
        out.push_str(&format!("run-as = {}\n", user));
    }

    // Working directory
    if let Some(ref dir) = service.working_dir {
        out.push_str(&format!("working-dir = {}\n", dir.display()));
    }

    // Logfile
    if let Some(ref path) = service.logfile {
        out.push_str(&format!("logfile = {}\n", path.display()));
    }

    // Pid file
    if let Some(ref path) = service.pid_file {
        out.push_str(&format!("pid-file = {}\n", path.display()));
    }

    // Env files
    for path in &service.env_files {
        out.push_str(&format!("env-file = {}\n", path.display()));
    }

    // Restart
    // dinit restarts by default, so systemd's default of no restart must be explicit
    match service.restart {
        RestartPolicy::Never => out.push_str("restart = false\n"),
        RestartPolicy::Always => out.push_str("restart = true\n"),
        RestartPolicy::OnFailure => out.push_str("restart = on-failure\n"),
    }

    // Smooth recovery
    if service.smooth_recovery {
        out.push_str("smooth-recovery = true\n");
    }

    // Restart delay
    if let Some(delay) = service.restart_delay {
        if delay == delay.floor() && delay.is_finite() {
            out.push_str(&format!("restart-delay = {}\n", delay as i64));
        } else {
            out.push_str(&format!("restart-delay = {}\n", delay));
        }
    }

    // Dependencies
    for dep in &service.depends_on {
        out.push_str(&format!("depends-on = {}\n", dep));
    }
    for dep in &service.waits_for {
        out.push_str(&format!("waits-for = {}\n", dep));
    }
    for dep in &service.after {
        out.push_str(&format!("after = {}\n", dep));
    }
    for dep in &service.before {
        out.push_str(&format!("before = {}\n", dep));
    }

    out
}
