// SPDX-FileCopyrightText: Hadi Cherkaoui <contact@hide.cherkaoui.ch>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

use std::io::{self, BufRead};
use std::path::{Path, PathBuf};

use crate::config::Config;
use crate::converter;
use crate::generator;
use crate::model::Severity;
use crate::parser::SystemdUnit;
use crate::services::KnownServices;

/// Returns `true` when `path` is a user-scope systemd unit
/// (`usr/lib/systemd/user/` or `/usr/lib/systemd/user/`).
#[must_use]
pub fn is_user_unit(path: &Path) -> bool {
    path.components()
        .zip(path.components().skip(1))
        .any(|(a, b)| a.as_os_str() == "systemd" && b.as_os_str() == "user")
}

/// Deletes all files generated by sd2dinit for a given service name.
///
/// Stops the service first via `dinitctl` (best-effort; ignored if dinit is
/// not running or the service was never loaded).
fn remove_unit(name: &str, output_dir: &Path) {
    // Best-effort stop — ignore all errors (service may not be loaded).
    let _ = std::process::Command::new("dinitctl")
        .args(["stop", name])
        .output();

    // All file suffixes that sd2dinit may have generated for this service.
    const SUFFIXES: &[&str] = &[
        "", "-pre", "-post", "-pre.sh", "-post.sh", "-stop.sh", ".env",
    ];

    for suffix in SUFFIXES {
        let path = output_dir.join(format!("{}{}", name, suffix));
        if path.exists() {
            match std::fs::remove_file(&path) {
                Ok(()) => eprintln!("  removed: {}", path.display()),
                Err(e) => eprintln!("  warn: could not remove {}: {}", path.display(), e),
            }
        }
    }
}

/// One `.service` path from pacman's target list that sd2dinit acts on.
#[derive(Debug)]
struct Target {
    full_path: PathBuf,
    name: String,
    user: bool,
}

/// Reads pacman's target list from stdin and converts or removes each unit.
///
/// # Errors
///
/// Returns an error if stdin cannot be read. Per-unit failures are reported on
/// stderr and counted as skipped instead.
pub fn run_hook(config: &Config) -> anyhow::Result<()> {
    let lines = io::stdin().lock().lines().collect::<Result<Vec<_>, _>>()?;
    process_targets(&lines, config);
    Ok(())
}

/// Converts or removes the units named in `lines`, one path per line.
///
/// Paths may be relative to `/`, as pacman passes them. All lines are read
/// before anything is converted, so a unit may depend on another unit from the
/// same transaction even though its dinit service does not exist yet.
pub fn process_targets(lines: &[String], config: &Config) {
    let mut removed = 0u32;
    let mut skipped = 0u32;
    let mut targets = Vec::new();

    for line in lines {
        let path = PathBuf::from(line.trim());

        // Only process .service files
        if path.extension().map(|e| e != "service").unwrap_or(true) {
            continue;
        }
        let Some(name) = path.file_stem().and_then(|s| s.to_str()).map(str::to_owned) else {
            continue;
        };

        // Skip template units
        if name.contains('@') {
            eprintln!("  skip: template unit {}", path.display());
            skipped += 1;
            continue;
        }

        // Check ignored list
        if let Some(file) = path.file_name().and_then(|s| s.to_str())
            && config.ignored_units.iter().any(|u| u == file)
        {
            skipped += 1;
            continue;
        }

        // Paths from the pacman hook are relative to filesystem root (e.g. "usr/lib/...")
        let full_path = if path.is_absolute() {
            path.clone()
        } else {
            PathBuf::from("/").join(&path)
        };
        let user = is_user_unit(&path);

        if full_path.exists() {
            targets.push(Target {
                full_path,
                name,
                user,
            });
            continue;
        }

        // File was removed by pacman — clean up the generated dinit service.
        let output_dir = output_dir_for(config, user);
        if output_dir.join(&name).exists() {
            let scope = if user { "user" } else { "system" };
            eprintln!("  removing [{}]: {}", scope, name);
            remove_unit(&name, output_dir);
            removed += 1;
        }
    }

    // Scanned after removals, so a unit dropped in this transaction no longer counts.
    let mut system_dirs = config.service_dirs.clone();
    system_dirs.push(config.output_dir.clone());
    let mut user_dirs = config.user_service_dirs.clone();
    user_dirs.push(config.user_output_dir.clone());
    let mut known_system = KnownServices::scan(&system_dirs);
    let mut known_user = KnownServices::scan(&user_dirs);
    for target in &targets {
        let known = if target.user {
            &mut known_user
        } else {
            &mut known_system
        };
        known.insert(target.name.clone());
    }

    let mut converted = 0u32;
    for target in &targets {
        let (output_dir, known, scope) = if target.user {
            (&config.user_output_dir, &known_user, "user")
        } else {
            (&config.output_dir, &known_system, "system")
        };
        match convert_unit(&target.full_path, output_dir, config, known) {
            Ok(name) => {
                eprintln!("  converted [{}]: {}", scope, name);
                converted += 1;
            }
            Err(e) => {
                eprintln!("  error converting {}: {:#}", target.full_path.display(), e);
                skipped += 1;
            }
        }
    }

    eprintln!(
        "sd2dinit hook: {} converted, {} removed, {} skipped",
        converted, removed, skipped
    );
}

/// User-scope units go to `user_output_dir` so every user's dinit sees them;
/// system units go to `output_dir` for the root instance.
fn output_dir_for(config: &Config, user: bool) -> &Path {
    if user {
        &config.user_output_dir
    } else {
        &config.output_dir
    }
}

fn convert_unit(
    path: &Path,
    output_dir: &Path,
    config: &Config,
    known: &KnownServices,
) -> anyhow::Result<String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| anyhow::anyhow!("failed to read {}: {}", path.display(), e))?;

    let unit = SystemdUnit::parse(&content, path.to_path_buf())
        .map_err(|e| anyhow::anyhow!("parse error: {}", e))?;

    let result = converter::convert(&unit, config, known)
        .map_err(|e| anyhow::anyhow!("convert error: {}", e))?;

    // Print warnings
    for w in &result.warnings {
        let prefix = match w.severity {
            Severity::Info => "info",
            Severity::Warn => "warn",
            Severity::Error => "error",
        };
        eprintln!("    {}: [{}] {}", prefix, w.directive, w.message);
    }

    // Write main service
    write_service_file(
        output_dir,
        &result.main_service.name,
        &generator::generate(&result.main_service),
    )?;

    // Write pre/post services
    if let Some(ref pre) = result.pre_service {
        write_service_file(output_dir, &pre.name, &generator::generate(pre))?;
    }
    if let Some(ref post) = result.post_service {
        write_service_file(output_dir, &post.name, &generator::generate(post))?;
    }

    // Write scripts
    if let Some(ref script) = result.pre_script {
        write_script_file(
            output_dir,
            &format!("{}-pre.sh", result.main_service.name),
            script,
        )?;
    }
    if let Some(ref script) = result.post_script {
        write_script_file(
            output_dir,
            &format!("{}-post.sh", result.main_service.name),
            script,
        )?;
    }
    if let Some(ref script) = result.stop_script {
        write_script_file(
            output_dir,
            &format!("{}-stop.sh", result.main_service.name),
            script,
        )?;
    }

    // Write env file
    if let Some(ref env_content) = result.env_file_content {
        let env_path = output_dir.join(format!("{}.env", result.main_service.name));
        std::fs::write(&env_path, env_content)
            .map_err(|e| anyhow::anyhow!("failed to write {}: {}", env_path.display(), e))?;
    }

    Ok(result.main_service.name.clone())
}

fn write_service_file(output_dir: &Path, name: &str, content: &str) -> anyhow::Result<()> {
    let path = output_dir.join(name);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| anyhow::anyhow!("failed to create dir {}: {}", parent.display(), e))?;
    }
    std::fs::write(&path, content)
        .map_err(|e| anyhow::anyhow!("failed to write {}: {}", path.display(), e))
}

fn write_script_file(output_dir: &Path, name: &str, content: &str) -> anyhow::Result<()> {
    let path = output_dir.join(name);
    std::fs::write(&path, content)
        .map_err(|e| anyhow::anyhow!("failed to write {}: {}", path.display(), e))?;

    // Make executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| anyhow::anyhow!("failed to chmod {}: {}", path.display(), e))?;
    }

    Ok(())
}
